<a href="https://colab.research.google.com/github/HaticeTuran/Data_analysis_methods_examples/blob/main/Pr%C3%BCfungsvorbereitung_DatenAnalyse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prüfungsvorbereitung

In [1]:
import numpy as np
import pandas as pd


In [2]:
my_arr = np.arange(1_000_000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [4]:
my_list = list(range(1_000_000))
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [5]:
#mehr diemnsion
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [6]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [8]:
print(data.shape) 
print(data.dtype) 

(2, 3)
float64


In [12]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr2

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [17]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [18]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

print(names == "Bob")
print(data[names == "Bob"])

#negative
print(~(names == "Bob"))

[ True False False  True False False False]
[[4 7]
 [0 0]]
[False  True  True False  True  True  True]


In [22]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [24]:
samples = np.random.standard_normal(size=(4, 4))

samples

array([[ 0.14748204,  0.51006664, -0.08128305, -1.49183059],
       [-1.06281497,  0.15861937, -0.38283999,  0.37783692],
       [-1.32828455, -1.36243447,  0.66774119,  0.39106717],
       [-0.60945766, -0.32095835,  0.11137662, -0.33893377]])

In [25]:
rng = np.random.default_rng(seed=12345)

data = rng.standard_normal((2, 3))
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [30]:
arr = np.arange(10)

np.save("some_array", arr)

np.load("some_array.npy")

np.savez("array_archive.npz", a=arr, b=arr)

In [31]:
arch = np.load("array_archive.npz")

arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

PANDAS

In [34]:
#Series

obj = pd.Series([4, 7, -5, 3])

print(obj)

print(obj.array)

0    4
1    7
2   -5
3    3
dtype: int64
<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64


In [35]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
print(obj2)

d    4
b    7
a   -5
c    3
dtype: int64


In [36]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

obj3 = pd.Series(sdata)

print(obj3)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


In [38]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [39]:
states = ["California", "Ohio", "Oregon", "Texas"]

obj4 = pd.Series(sdata, index=states)

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [40]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [41]:
#Frame
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [42]:
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [43]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [45]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [46]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [47]:
frame2["debt"] = np.arange(6.)

In [48]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [50]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   0.0     True
1  2001    Ohio  1.7   1.0     True
2  2002    Ohio  3.6   2.0     True
3  2001  Nevada  2.4   3.0    False
4  2002  Nevada  2.9   4.0    False
5  2003  Nevada  3.2   5.0    False

In [52]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}

frame3 = pd.DataFrame(populations)

frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [54]:
frame3.index.name = "year"

frame3.columns.name = "state"

frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [55]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [56]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

index = obj.index

index

Index(['a', 'b', 'c'], dtype='object')

In [58]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [59]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [60]:
states = ["Texas", "Utah", "California"]

frame.reindex(columns=states)

Texas  Utah  California
0    NaN   NaN         NaN
1    NaN   NaN         NaN
2    NaN   NaN         NaN
3    NaN   NaN         NaN
4    NaN   NaN         NaN
5    NaN   NaN         NaN

In [61]:
#DROP
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                     index=["Ohio", "Colorado", "Utah", "New York"], 
                     columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [62]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [63]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [64]:
#indesing, selection, filtering

obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [65]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

obj1

2    1
0    2
1    3
dtype: int64

In [68]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [69]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [70]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [73]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [74]:
#arithmetic 

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [75]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [76]:
df1.add(df2, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

#func application & mapping

In [77]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah   -0.946130 -0.254083 -2.148348
Ohio   -0.340740 -0.350056  0.409868
Texas   0.534673 -0.399402  1.419683
Oregon  0.494347  0.609023  1.625331

In [78]:
def f1(x):
  return x.max() - x.min()

frame.apply(f1)

b    1.480802
d    1.008424
e    3.773679
dtype: float64

In [79]:
def my_format(x):
  return f"{x:.2f}"

frame.applymap(my_format)

b      d      e
Utah    -0.95  -0.25  -2.15
Ohio    -0.34  -0.35   0.41
Texas    0.53  -0.40   1.42
Oregon   0.49   0.61   1.63

In [80]:
#inexing and sorting

obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [81]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [82]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [83]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

print(frame)

frame.sort_values("b")

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1


b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [84]:
 obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
 obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [85]:
obj.describe()

count    7.000000
mean     2.714286
std      4.231402
min     -5.000000
25%      1.000000
50%      4.000000
75%      5.500000
max      7.000000
dtype: float64

In [86]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [87]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [ ]:
#reading, storage files
result = pd.read_csv("examples/ex3.txt", sep="\s+")
data.to_csv("examples/out.csv")

Handling missing data

In [88]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [89]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [90]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
print(data)
data.dropna() # data[data.notna()]

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64


0    1.0
2    3.5
4    7.0
dtype: float64

In [91]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [92]:
data.fillna(0)

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

Discretization and Binning

In [94]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

bins = [18, 25, 35, 60, 100]

In [95]:
age_categories = pd.cut(ages, bins)

age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [96]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [97]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [98]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

pd.cut(ages, bins, labels=group_names)


['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [99]:
data = np.random.standard_normal(1000)

quartiles = pd.qcut(data, 4, precision=2)

quartiles

[(0.62, 3.91], (-0.0033, 0.62], (-0.0033, 0.62], (-0.69, -0.0033], (-0.0033, 0.62], ..., (-0.69, -0.0033], (-3.28, -0.69], (-3.28, -0.69], (0.62, 3.91], (-3.28, -0.69]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.28, -0.69] < (-0.69, -0.0033] < (-0.0033, 0.62] <
                                           (0.62, 3.91]]

In [100]:
pd.value_counts(quartiles)

(-3.28, -0.69]      250
(-0.69, -0.0033]    250
(-0.0033, 0.62]     250
(0.62, 3.91]        250
dtype: int64

In [101]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": range(6)})

print(df)

pd.get_dummies(df["key"])

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5


a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

Regex

In [102]:
import re

pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

regex = re.compile(pattern, flags=re.IGNORECASE)

In [103]:
m = regex.match("wesm@bright.net")

m.groups()


('wesm', 'bright', 'net')


Categorical Data


In [ ]:
#Categorical Data



In [104]:
values = pd.Series(['apple', 'orange', 'apple','apple'] * 2)

values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [105]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [107]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [108]:
values = pd.Series([0, 1, 0, 0] * 2)

dim = pd.Series(['apple', 'orange'])

values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [110]:
dim

0     apple
1    orange
dtype: object

In [111]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [113]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

N = len(fruits)

rng = np.random.default_rng(seed=12345)

df = pd.DataFrame({'fruit': fruits,
                'basket_id': np.arange(N),
                'count': rng.integers(3, 15, size=N),
                'weight': rng.uniform(0, 4, size=N)},
               columns=['basket_id', 'fruit', 'count', 'weight'])

df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [114]:
fruit_cat = df['fruit'].astype('category')

fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [115]:
c = fruit_cat.array

type(c)

pandas.core.arrays.categorical.Categorical

In [116]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [117]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [118]:
#Computations with Categoricals

rng = np.random.default_rng(seed=12345)

draws = rng.standard_normal(1000)

draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])